Repository endlessm/everlasting-candy, pull requests merged in 2025-01, with the labels that each got.

#6 README: Rewrite for the fork
  README.md
  readme.md
Labels: Documentation, Maintenance

#21 Document adding new worlds and editing levels
  README.md
Labels: Documentation

#33 Add Game Design Document
  doc/GameDesign.md
Labels: Design, Maintenance

#40 Set loop property on OST sample
  Audio/OST.mp3.import
  Script/Global.gd
Labels: Bitesize, Engineering

#28 Add scrolling to world selector
  Scene/WorldSelector.tscn
  Scene/WorldSelector/ExtraWorldSelector.tscn
  Scene/WorldSelector/MainWorldSelector.tscn
  Script/WorldSelector.gd
  Script/WorldSelector/ExtraWorldSelector.gd
  Script/WorldSelector/MainWorldSelector.gd
  Theme/WorldSelector.tres
Labels: Design, Engineering
